name: Test Module

on:
  pull_request:
    paths:
      - '*.tf'
      - 'tests/**'
      - 'examples/**'
      - '.github/workflows/terraform-test.yml'
  workflow_dispatch:

env:
  AWS_REGION: 'ap-southeast-1'
  TF_VERSION: '1.6.0'
  GO_VERSION: '1.21'

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init (Main Module)
        run: terraform init -backend=false

      - name: Terraform Validate (Main Module)
        run: terraform validate

      - name: Terraform Init (Test Example)
        run: |
          cd examples/domain-verification
          terraform init -backend=false
          cd ../email-verification
          terraform init -backend=false

      - name: Terraform Validate (Test Example)
        run: |
          cd examples/domain-verification
          terraform validate
          cd ../email-verification
          terraform validate

      - name: Comment PR on validation failure
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const buildUrl = `${context.payload.repository.html_url}/actions/runs/${context.runId}`;
            const commentBody = `@claude fix build error:\n\n**Build Link:** ${buildUrl}\n\n## ❌ Terraform Validation Failed\n\nTerraform validation or formatting check failed. Please check the workflow logs for details.`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody,
            });

  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Download Go Dependencies
        run: |
          cd tests
          go mod download

      - name: Run Go Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          working-directory: tests

      - name: Comment PR on lint failure
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const buildUrl = `${context.payload.repository.html_url}/actions/runs/${context.runId}`;
            const commentBody = `@claude fix build error:\n\n**Build Link:** ${buildUrl}\n\n## ❌ Go Lint Failed\n\nGo linting failed. Please check the workflow logs for details and fix the linting issues.`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody,
            });

  test:
    name: Run Full Test Suite
    runs-on: ubuntu-latest
    needs: [validate, lint]
    environment: testing
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download Go Dependencies
        run: |
          cd tests
          go mod download

      - name: Run integration tests with reporting
        id: test
        working-directory: ./tests
        run: |
          echo "Running Terraform integration tests with reporting..."
          go test -v -timeout 30m -report -report-file=test-report.json -html-file=test-report.html
          TEST_EXIT_CODE=$?
          
          # Save test results for PR comment
          if [ -f test-results.json ]; then
            test_results=$(< test-results.json)
            printf "test_results<<EOF\n%s\nEOF\n" "$test_results" >> "$GITHUB_OUTPUT"
          fi

          # Save summary for PR comment
          if [ -f test-summary.md ]; then
            test_summary=$(< test-summary.md)
            printf "test_summary<<EOF\n%s\nEOF\n" "$test_summary" >> "$GITHUB_OUTPUT"
          fi

          exit $TEST_EXIT_CODE
          
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            tests/test-report.json
            tests/test-report.html
            tests/test-summary.md
            
      - name: Comment PR with test results
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const summary = `${{ steps.test.outputs.test_summary }}`;
            const testExitCode = '${{ steps.test.outcome }}';
            const buildUrl = `${context.payload.repository.html_url}/actions/runs/${context.runId}`;
            
            // Find existing comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('🧪 Terraform AWS SES Test Results')
            );
            
            let commentBody;
            
            if (testExitCode === 'failure') {
              // If tests failed, add @claude prefix and build link
              commentBody = `@claude fix build error:\n\n**Build Link:** ${buildUrl}\n\n${summary || '## 🧪 Terraform AWS SES Test Results\n\nTest execution failed. Please check the workflow logs for details.'}`;
            } else {
              // For successful tests or other outcomes
              commentBody = summary || '## 🧪 Terraform AWS SES Test Results\n\nTest report generation failed. Please check the workflow logs.';
            }
            
            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: commentBody,
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody,
              });
            }

      - name: Comment PR on test failure
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const buildUrl = `${context.payload.repository.html_url}/actions/runs/${context.runId}`;
            const commentBody = `@claude fix build error:\n\n**Build Link:** ${buildUrl}\n\n## ❌ Test Failed\n\nTest failed. Please check the workflow logs for details and fix the issues.`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody,
            });